repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
        files: ^User/(?!.*\/ST\/).+$
      - id: end-of-file-fixer
        files: ^User/(?!.*\/ST\/).+$
      - id: trailing-whitespace
        files: ^User/(?!.*\/ST\/).+$

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
      - id: clang-format
        args: [--style=file]
        files: ^User/(?!.*\/ST\/).+$
