repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
        include: ^User/.*$
      - id: end-of-file-fixer
        include: ^User/.*$
      - id: trailing-whitespace
        include: ^User/.*$

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v12.0.1
    hooks:
      - id: clang-format
        args: [--style=file]
        include: ^User/.*$
